version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_CACHE_DIR: ~/repo/pipenv-cache

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip3 install pipenv --user
            python3 -m pipenv install --dev

      - save_cache:
          paths:
            - ./pipenv-cache
          key: v1-dependencies-{{ checksum "Pipfile" }}

      - run:
          name: run tests
          command: |
            python3 -m pipenv run pytest

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "62:72:3a:58:97:e4:92:5e:9b:b4:ca:ee:2d:19:ef:65"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy.sh $CIRCLE_BRANCH"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:  /^release/\d+\.\d+\.\d+/
